services:
  frontend:
    image: prajwalnav/frontend
    ports:
      - "80:3000"
    depends_on:
      - backend

  backend:
    image: prajwalnav/backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongo:27017/dd_db
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nginx:
    image: prajwalnav/nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data:
